Update orchestration

diff --git a/orchestration b/orchestration
--- a/orchestration
+++ b/orchestration
@@ -131,6 +131,7 @@ D 'PiHole: Maintenance' \
 E 'Nextcloud: filelocks' \
 F 'Nextcloud: add-missing-indices' \
 G 'Nextcloud: check-core' \
+H 'Nextcloud: Disable LDAP' \
 X '<' 2>&1 > /dev/tty )
 case "$var0" in
 A) clear ; restorebkp ;;
@@ -140,13 +141,14 @@ D) clear ; piholemnt ;;
 E) clear ; filelocks ;;
 F) clear ; missingindices ;;
 G) clear ; checkcore ;;
+H) clear ; disableldap ;;
 X) echo "." > /dev/null ;;
 esac
 }
 
-function missingindices {
+function disableldap {
 VALUE1="nextcloud"
-VALUE0=$(dialog --ok-label "Ok" --title "Manutenção" --form "MySQL - NextCloud" 9 35 0 \
+VALUE0=$(dialog --ok-label "Ok" --title "Manutencao" --form "Disable LDAP" 9 35 0 \
 "NextCont:" 1 1 "$VALUE1" 1 11 30 0 \
 3>&1 1>&2 2>&3 3>&- > /dev/tty)
 
@@ -158,14 +160,34 @@ VALUE0=$(dialog --ok-label "Ok" --title "Manutenção" --form "MySQL - NextCloud
     var1=$(echo "$VALUE0" | sed -n 1p)
 
     clear
-    echo "Checking missing indices:"
-    docker exec -u 33 "$var1" ./occ integrity:check-core
+    echo "Disabling LDAP Backend!"
+    docker exec -u 33 "$var1" ./occ ldap:set-config "s01" "ldapConfigurationActive" "0"
+    sleep 2
+    docker restart "$var1"
     sleep 5
 }
 
 function checkcore {
 VALUE1="nextcloud"
-VALUE0=$(dialog --ok-label "Ok" --title "Manutenção" --form "MySQL - NextCloud" 9 35 0 \
+VALUE0=$(dialog --ok-label "Ok" --title "Manutencao" --form "Nextcloud" 9 35 0 \
+"NextCont:" 1 1 "$VALUE1" 1 11 30 0 \
+3>&1 1>&2 2>&3 3>&- > /dev/tty)
+
+    case $? in
+      0) echo "." > /dev/null ;;
+      1) exit ;;
+    esac
+
+    var1=$(echo "$VALUE0" | sed -n 1p)
+    clear
+    echo "Checking core integrity..."
+    docker exec -u 33 "$var1" ./occ integrity:check-core
+    sleep 5
+}
+
+function missingindices {
+VALUE1="nextcloud"
+VALUE0=$(dialog --ok-label "Ok" --title "Manutencao" --form "Nextcloud" 9 35 0 \
 "NextCont:" 1 1 "$VALUE1" 1 11 30 0 \
 3>&1 1>&2 2>&3 3>&- > /dev/tty)
 
@@ -177,13 +199,13 @@ VALUE0=$(dialog --ok-label "Ok" --title "Manutenção" --form "MySQL - NextCloud
     var1=$(echo "$VALUE0" | sed -n 1p)
 
     clear
-    echo "Checking core integrity:"
+    echo "Adding missing indices..."
     docker exec -u 33 "$var1" ./occ db:add-missing-indices
     sleep 5
 }
 
 function piholemnt {
-VALUE0=$(dialog --ok-label "Ok" --title "Manutenção" --form "PiHole" 8 35 0 \
+VALUE0=$(dialog --ok-label "Ok" --title "Manutencao" --form "PiHole" 8 35 0 \
 "NomeCont:" 1 1 "$VALUE1" 1 11 30 0 \
 3>&1 1>&2 2>&3 3>&- > /dev/tty)
 
@@ -202,7 +224,7 @@ VALUE0=$(dialog --ok-label "Ok" --title "Manutenção" --form "PiHole" 8 35 0 \
 function filelocks {
 VALUE1="nextcloud-mysql"
 
-VALUE0=$(dialog --ok-label "Ok" --title "Manutenção" --form "MySQL - NextCloud" 9 35 0 \
+VALUE0=$(dialog --ok-label "Ok" --title "Manutencao" --form "MySQL - NextCloud" 9 35 0 \
 "mSQLcont:" 1 1 "$VALUE1" 1 11 30 0 \
 "Password:" 2 1 "$VALUE2" 2 11 30 0 \
 3>&1 1>&2 2>&3 3>&- > /dev/tty)
