Update orchestration

diff --git a/orchestration b/orchestration
--- a/orchestration
+++ b/orchestration
@@ -124,7 +124,9 @@ A 'Retore a Backup' \
 B 'Set MACVLAN' \
 C 'Remove MACVLAN' \
 D 'PiHole: Maintenance' \
-E 'Nextcloud: Clear FileLocks' \
+E 'Nextcloud: filelocks' \
+F 'Nextcloud: add-missing-indices' \
+G 'Nextcloud: check-core' \
 X '<' 2>&1 > /dev/tty )
 case "$var0" in
 A) clear ; restorebkp ;;
@@ -132,8 +134,46 @@ B) clear ; macvland ;;
 C) clear ; docker network rm macvlan ; sleep 2 ;;
 D) clear ; piholemnt ;;
 E) clear ; filelocks ;;
+F) clear ; missingindices ;;
+G) clear ; checkcore ;;
 X) echo "." > /dev/null ;;
 esac
+}
+
+function missingindices {
+VALUE0=$(dialog --ok-label "Ok" --title "Manutenção" --form "MySQL - NextCloud" 9 35 0 \
+"NextCont:" 1 1 "$VALUE1" 1 11 30 0 \
+3>&1 1>&2 2>&3 3>&- > /dev/tty)
+
+    case $? in
+      0) echo "." > /dev/null ;;
+      1) exit ;;
+    esac
+
+    var1=$(echo "$VALUE0" | sed -n 1p)
+
+    clear
+    echo "Checking missing indices:"
+    docker exec -u 33 "$var1" ./occ integrity:check-core
+    sleep 5
+}
+
+function checkcore {
+VALUE0=$(dialog --ok-label "Ok" --title "Manutenção" --form "MySQL - NextCloud" 9 35 0 \
+"NextCont:" 1 1 "$VALUE1" 1 11 30 0 \
+3>&1 1>&2 2>&3 3>&- > /dev/tty)
+
+    case $? in
+      0) echo "." > /dev/null ;;
+      1) exit ;;
+    esac
+
+    var1=$(echo "$VALUE0" | sed -n 1p)
+
+    clear
+    echo "Checking core integrity:"
+    docker exec -u 33 "$var1" ./occ db:add-missing-indices
+    sleep 5
 }
 
 function piholemnt {
